## We seek to first apporximate the current Pixel Threshold by identifying the partition of greatest length within the current DES DR2 Catalog

In [12]:
import sys
import os

parent_dir = os.path.abspath('..')
if parent_dir not in sys.path:
    sys.path.insert(0, parent_dir)

from pathlib import Path
import importlib

import numpy as np
import pandas as pd
from astropy.io import ascii
import matplotlib.pyplot as plt

from dask.distributed import Client
import dask.array
from dask.dataframe.utils import make_meta

from hats import read_hats
from hats.inspection import plot_pixels
from hats_import.catalog.file_readers import CsvReader
from hats_import.margin_cache.margin_cache_arguments import MarginCacheArguments
from hats_import.pipeline import ImportArguments, pipeline_with_client

import lsdb

from catalog_filtering import bandFilterLenient, contains_PM
import hpms_pipeline as hpms

print("Imported libraries.")

Imported libraries.

In [14]:
from hats_import.pipeline import pipeline_with_client
from hats_import.catalog.arguments import ImportArguments

In [15]:
CATALOG_DIR = Path("../../../catalogs")
MARGIN_CACHE_DIR = CATALOG_DIR / 'margin_caches'

DES_NAME = "des_light"
DES_DIR = CATALOG_DIR / DES_NAME 

DES_MARGIN_CACHE_NAME = "des_margin_cache_18_arcsec"
DES_MARGIN_CACHE_DIR = MARGIN_CACHE_DIR / DES_MARGIN_CACHE_NAME

In [16]:
des_dr2 = lsdb.read_hats(DES_DIR)
des_dr2

Dask NestedFrame Structure:
                        CLASS_STAR_G     CLASS_STAR_R     CLASS_STAR_I     CLASS_STAR_Z     CLASS_STAR_Y         FLAGS_G         FLAGS_R         FLAGS_I         FLAGS_Z         FLAGS_Y               RA              DEC COADD_OBJECT_ID   SPREAD_MODEL_G   SPREAD_MODEL_R   SPREAD_MODEL_I   SPREAD_MODEL_Z   SPREAD_MODEL_Y   WAVG_MAG_PSF_G   WAVG_MAG_PSF_R   WAVG_MAG_PSF_I   WAVG_MAG_PSF_Z   WAVG_MAG_PSF_Y WAVG_MAGERR_PSF_G WAVG_MAGERR_PSF_R WAVG_MAGERR_PSF_I WAVG_MAGERR_PSF_Z WAVG_MAGERR_PSF_Y       NEPOCHS_G       NEPOCHS_R       NEPOCHS_I       NEPOCHS_Z       NEPOCHS_Y
npartitions=1582
0                    double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  int16[pyarrow]  int16[pyarrow]  int16[pyarrow]  int16[pyarrow]  int16[pyarrow]  double[pyarrow]  double[pyarrow]  int64[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]   double[pyarrow]   double[pyarrow]   double[pyarrow]   double[pyarrow]   double[pyarrow]  int32[pyarrow]  int32[pyarrow]  int32[pyarrow]  int32[pyarrow]  int32[pyarrow]
2251799813685248                 ...              ...              ...              ...              ...             ...             ...             ...             ...             ...              ...              ...             ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...               ...               ...               ...               ...               ...             ...             ...             ...             ...             ...
...                              ...              ...              ...              ...              ...             ...             ...             ...             ...             ...              ...              ...             ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...               ...               ...               ...               ...               ...             ...             ...             ...             ...             ...
3386706919782612992              ...              ...              ...              ...              ...             ...             ...             ...             ...             ...              ...              ...             ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...               ...               ...               ...               ...               ...             ...             ...             ...             ...             ...
3458764513820540928              ...              ...              ...              ...              ...             ...             ...             ...             ...             ...              ...              ...             ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...               ...               ...               ...               ...               ...             ...             ...             ...             ...             ...
Dask Name: nestedframe, 3 expressions
Expr=MapPartitions(NestedFrame)

In [17]:
with Client():
    partition_lengths = des_dr2.map_partitions(len).compute()
partition_lengths

/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/dask/dataframe/dask_expr/_expr.py:4078: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/lsdb/catalog/dataset/healpix_dataset.py:534: RuntimeWarning: output of the function must be a DataFrame to generate an LSDB `Catalog`. `map_partitions` will return a dask object instead of a Catalog.
  warnings.warn(

0    838930
0    408866
      ...
0      2926
0    289866
Length: 1582, dtype: int64

In [18]:
partition_lengths.max()

np.int64(971062)

## Let us assume that the current Pixel Threshold is $\bf{1,000,000}$, let's change this to $\bf{100,000}$

In [27]:
# Reimport Args:

output_name = "des_dr2_pix_thresh_100k"
OUTPUT_DIR = CATALOG_DIR
output_artifact_name= output_name
pixel_thresh=100000
highest_healpix_order = 10

args = ImportArguments.reimport_from_hats(
        DES_DIR,
        OUTPUT_DIR,
        output_artifact_name=output_name,
        pixel_threshold=pixel_thresh,
        highest_healpix_order=10
)

Validating catalog at path ../../../catalogs/des_light ...
Found 1582 partitions.
Approximate coverage is 30.99 % of the sky.

In [28]:
with Client(n_workers = 10) as client:
    display(client)
    pipeline_with_client(args, client)

/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/node.py:187: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 33565 instead
  warnings.warn(

Planning  :   0%|          | 0/4 [00:00<?, ?it/s]

Mapping   :   0%|          | 0/1582 [00:00<?, ?it/s]

Binning   :   0%|          | 0/2 [00:00<?, ?it/s]

Splitting :   0%|          | 0/1582 [00:00<?, ?it/s]

Reducing  :   0%|          | 0/23044 [00:00<?, ?it/s]

Finishing :   0%|          | 0/5 [00:00<?, ?it/s]

2025-10-04 22:16:02,847 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2025-10-04 22:16:02,847 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2025-10-04 22:16:02,848 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2025-10-04 22:16:02,849 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2025-10-04 22:16:02,849 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2025-10-04 22:16:02,850 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2025-10-04 22:16:02,850 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2025-10-04 22:16:02,851 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2025-10-04 22:16:02,852 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2025-10-04 22:16:02,852 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing

In [30]:
des_pix_100k = lsdb.read_hats(OUTPUT_DIR / output_name)
des_pix_100k

Dask NestedFrame Structure:
                        CLASS_STAR_G     CLASS_STAR_R     CLASS_STAR_I     CLASS_STAR_Z     CLASS_STAR_Y         FLAGS_G         FLAGS_R         FLAGS_I         FLAGS_Z         FLAGS_Y               RA              DEC COADD_OBJECT_ID   SPREAD_MODEL_G   SPREAD_MODEL_R   SPREAD_MODEL_I   SPREAD_MODEL_Z   SPREAD_MODEL_Y   WAVG_MAG_PSF_G   WAVG_MAG_PSF_R   WAVG_MAG_PSF_I   WAVG_MAG_PSF_Z   WAVG_MAG_PSF_Y WAVG_MAGERR_PSF_G WAVG_MAGERR_PSF_R WAVG_MAGERR_PSF_I WAVG_MAGERR_PSF_Z WAVG_MAGERR_PSF_Y       NEPOCHS_G       NEPOCHS_R       NEPOCHS_I       NEPOCHS_Z       NEPOCHS_Y
npartitions=23044
0                    double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  int16[pyarrow]  int16[pyarrow]  int16[pyarrow]  int16[pyarrow]  int16[pyarrow]  double[pyarrow]  double[pyarrow]  int64[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]   double[pyarrow]   double[pyarrow]   double[pyarrow]   double[pyarrow]   double[pyarrow]  int32[pyarrow]  int32[pyarrow]  int32[pyarrow]  int32[pyarrow]  int32[pyarrow]
105553116266496                  ...              ...              ...              ...              ...             ...             ...             ...             ...             ...              ...              ...             ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...               ...               ...               ...               ...               ...             ...             ...             ...             ...             ...
...                              ...              ...              ...              ...              ...             ...             ...             ...             ...             ...              ...              ...             ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...               ...               ...               ...               ...               ...             ...             ...             ...             ...             ...
3454260914193170432              ...              ...              ...              ...              ...             ...             ...             ...             ...             ...              ...              ...             ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...               ...               ...               ...               ...               ...             ...             ...             ...             ...             ...
3458764513820540928              ...              ...              ...              ...              ...             ...             ...             ...             ...             ...              ...              ...             ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...               ...               ...               ...               ...               ...             ...             ...             ...             ...             ...
Dask Name: nestedframe, 3 expressions
Expr=MapPartitions(NestedFrame)

In [31]:
with Client(n_workers=8) as client:
    display(client)
    partition_lengths = des_pix_100k.map_partitions(len).compute()

/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/node.py:187: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 44223 instead
  warnings.warn(

/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/dask/dataframe/dask_expr/_expr.py:4078: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/lsdb/catalog/dataset/healpix_dataset.py:534: RuntimeWarning: output of the function must be a DataFrame to generate an LSDB `Catalog`. `map_partitions` will return a dask object instead of a Catalog.
  warnings.warn(
/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/client.py:3383: UserWarning: Sending large graph of size 10.74 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(
2025-10-04 22:30:26,590 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2025-10-04 22:30:26,591 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2025-10-04 22:30:27,591 - distributed.client - ERROR -
Traceback (most recent call last):
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/utils.py", line 1910, in wait_for
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/utils.py", line 805, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/client.py", line 1944, in _close
    await self.cluster.close()
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/deploy/spec.py", line 454, in _close
    await self._correct_state()
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/deploy/spec.py", line 365, in _correct_state_internal
    await asyncio.gather(*tasks)
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/nanny.py", line 619, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/nanny.py", line 400, in kill
    await self.process.kill(reason=reason, timeout=timeout)
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/nanny.py", line 883, in kill
    await process.join(max(0, deadline - time()))
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/utils.py", line 1909, in wait_for
    async with asyncio.timeout(timeout):
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
2025-10-04 22:30:27,593 - tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x1484adf563f0>>, <Task finished name='Task-20218642' coro=<SpecCluster._correct_state_internal() done, defined at /ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/deploy/spec.py:352> exception=TimeoutError()>)
Traceback (most recent call last):
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/utils.py", line 1910, in wait_for
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
          ^^^^^^^^^^
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/tornado/ioloop.py", line 782, in _discard_future_result
    future.result()
TimeoutError

TimeoutError: