# Creating Healpix Density Function
We seek to create a map_paritions function capable of finding the object density of the partitions within DES DR2. Density = N * 4^(-order), where order is the healpix order. From there, we will run the pipeline on this high density parition and analyze the results.

In [1]:
import sys
import os

parent_dir = os.path.abspath('..')
if parent_dir not in sys.path:
    sys.path.insert(0, parent_dir)

from pathlib import Path
import importlib

import numpy as np
import pandas as pd
from astropy.io import ascii
import matplotlib.pyplot as plt

from dask.distributed import Client
import dask.array
from dask.dataframe.utils import make_meta

from hats import read_hats
from hats.inspection import plot_pixels
from hats_import.catalog.file_readers import CsvReader
from hats_import.margin_cache.margin_cache_arguments import MarginCacheArguments
from hats_import.pipeline import ImportArguments, pipeline_with_client

import lsdb

from catalog_filtering import bandFilterLenient, contains_PM
import hpms_pipeline as hpms

print("Imported libraries.")

Imported libraries.

In [ ]:
bandList = ['G','R','I','Z','Y']
class_star = None
spread_model = 0.05
magnitude_error = 0.05
check_flags = True
mag = 19
query_string = bandFilterLenient(bandList,classStar=class_star,spreadModel=spread_model,magError=magnitude_error,flag=check_flags,mag=mag)
des_cols = (
    [f'CLASS_STAR_{band}' for band in bandList] + 
    [f'FLAGS_{band}' for band in bandList] + 
    ['RA','DEC','COADD_OBJECT_ID'] + 
    [f'SPREAD_MODEL_{band}' for band in bandList] + 
    [f'WAVG_MAG_PSF_{band}' for band in bandList] + 
    [f'WAVG_MAGERR_PSF_{band}' for band in bandList]
)
k = 2
max_obj_deviation = 0.2
des_id_col = 'COADD_OBJECT_ID_1'
mag_cols = [f'WAVG_MAG_PSF_{band}' for band in ['I']]
min_neighbors = 4
max_neighbor_dist = 24
xmatch_max_neighbors = 100
print("Defined globals.")

In [2]:
CATALOG_DIR = Path("../../../../catalogs")
MARGIN_CACHE_DIR = CATALOG_DIR / 'margin_caches'

DES_NAME = "des_light"
DES_DIR = CATALOG_DIR / DES_NAME 

DES_MARGIN_CACHE_NAME = "des_margin_cache_18_arcsec"
DES_MARGIN_CACHE_DIR = MARGIN_CACHE_DIR / DES_MARGIN_CACHE_NAME

In [16]:
def subset_len(df, pixel):
    return len(df) * (4.0 ** -(pixel[0])),
        "pixel_order": pixel[0],
        "pixel_index": pixel[1]
    }, index=[0])

In [4]:
des_dr2 = lsdb.read_hats(DES_DIR)
des_dr2

Dask NestedFrame Structure:
                        CLASS_STAR_G     CLASS_STAR_R     CLASS_STAR_I     CLASS_STAR_Z     CLASS_STAR_Y         FLAGS_G         FLAGS_R         FLAGS_I         FLAGS_Z         FLAGS_Y               RA              DEC COADD_OBJECT_ID   SPREAD_MODEL_G   SPREAD_MODEL_R   SPREAD_MODEL_I   SPREAD_MODEL_Z   SPREAD_MODEL_Y   WAVG_MAG_PSF_G   WAVG_MAG_PSF_R   WAVG_MAG_PSF_I   WAVG_MAG_PSF_Z   WAVG_MAG_PSF_Y WAVG_MAGERR_PSF_G WAVG_MAGERR_PSF_R WAVG_MAGERR_PSF_I WAVG_MAGERR_PSF_Z WAVG_MAGERR_PSF_Y       NEPOCHS_G       NEPOCHS_R       NEPOCHS_I       NEPOCHS_Z       NEPOCHS_Y
npartitions=1582
0                    double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  int16[pyarrow]  int16[pyarrow]  int16[pyarrow]  int16[pyarrow]  int16[pyarrow]  double[pyarrow]  double[pyarrow]  int64[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]   double[pyarrow]   double[pyarrow]   double[pyarrow]   double[pyarrow]   double[pyarrow]  int32[pyarrow]  int32[pyarrow]  int32[pyarrow]  int32[pyarrow]  int32[pyarrow]
2251799813685248                 ...              ...              ...              ...              ...             ...             ...             ...             ...             ...              ...              ...             ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...               ...               ...               ...               ...               ...             ...             ...             ...             ...             ...
...                              ...              ...              ...              ...              ...             ...             ...             ...             ...             ...              ...              ...             ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...               ...               ...               ...               ...               ...             ...             ...             ...             ...             ...
3386706919782612992              ...              ...              ...              ...              ...             ...             ...             ...             ...             ...              ...              ...             ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...               ...               ...               ...               ...               ...             ...             ...             ...             ...             ...
3458764513820540928              ...              ...              ...              ...              ...             ...             ...             ...             ...             ...              ...              ...             ...              ...              ...              ...              ...              ...              ...              ...              ...              ...              ...               ...               ...               ...               ...               ...             ...             ...             ...             ...             ...
Dask Name: nestedframe, 3 expressions
Expr=MapPartitions(NestedFrame)

In [17]:
client = Client()
with client:
    display(client)
    find_lens = des_dr2.map_partitions(subset_len, include_pixel=True).compute()
    
find_lens

2025-09-16 21:49:15,330 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/comm/tcp.py", line 226, in read
    frames_nosplit_nbytes_bin = await stream.read_bytes(fmt_size)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/utils_comm.py", line 416, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/utils_comm.py", line 395, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/comm/tcp.py", line 237, in read
    convert_stream_closed_error(self, e)
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/comm/tcp.py", line 137, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://127.0.0.1:49150 remote=tcp://127.0.0.1:44233>: Stream is closed
2025-09-16 21:49:15,394 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/comm/tcp.py", line 226, in read
    frames_nosplit_nbytes_bin = await stream.read_bytes(fmt_size)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/utils_comm.py", line 416, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/utils_comm.py", line 395, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/comm/tcp.py", line 237, in read
    convert_stream_closed_error(self, e)
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/comm/tcp.py", line 137, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://127.0.0.1:49168 remote=tcp://127.0.0.1:44233>: Stream is closed
2025-09-16 21:49:15,473 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/comm/tcp.py", line 226, in read
    frames_nosplit_nbytes_bin = await stream.read_bytes(fmt_size)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/utils_comm.py", line 416, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/utils_comm.py", line 395, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/comm/tcp.py", line 237, in read
    convert_stream_closed_error(self, e)
  File "/ocean/projects/phy210048p/jpassos/conda-venvs/lsdb-main/lib/python3.12/site-packages/distributed/comm/tcp.py", line 137, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://127.0.0.1:49138 remote=tcp://127.0.0.1:44233>: Stream is closed
2025-09-16 21:49:19,090 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2025-09-16 21:49:19,091 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2025-09-16 21:49:19,092 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2025-09-16 21:49:19,092 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing

         density  pixel_order  pixel_index
0    3277.070312            4            0
0     399.283203            5            8
..           ...          ...          ...
0      45.718750            3          743
0   72466.500000            1           47

[1582 rows x 3 columns]

In [24]:
densities = find_lens.reset_index(drop=True)
densities

           density  pixel_order  pixel_index
0      3277.070312            4            0
1       399.283203            5            8
...            ...          ...          ...
1580     45.718750            3          743
1581  72466.500000            1           47

[1582 rows x 3 columns]

In [30]:
max_density = densities.loc[densities['density'].idxmax()]
max_density

density        130306.5
pixel_order         1.0
pixel_index        22.0
Name: 402, dtype: float64

#### We see that pixel 22 (index 22) is the highest density healpix pixel for DES. We will use this to run memory performance testing. We will use Memray for memory analysis.

In [31]:
import memray

In [ ]:
high_density_parition = np.nan

In [ ]:
%%memray_flamegraph 

# memray kwargs to consider: --follow-fork, --leaks, --temporary-allocations, --temporal, --split-threads, --max-memory-records

hpms.execute_pipeline(high_density_parition, query_string, xmatch_max_neighbors,
                      max_neighbor_dist, min_neighbors, k,
                      max_obj_deviation, des_id_col, mag_cols).to_hats(catalog_name='two_deg_cs_2_results', 
                                                                       base_catalog_path=RESULTS_DIR)